version: '3'
services:
  # client:
  #   build: ./client/
  #   ports:
  #     - "3000:3000"
  #   command: yarn start
  #   volumes:
  #     - ./client/:/app
  #     - /node_modules
  #   depends_on:
  #     - backend

  backend:
    image: phoenix:1.4.0
    build: ./backend/
    command: ./start.sh
    ports:
      - "4000:4000"
    volumes:
      - ./backend/:/app
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: