version: '3'
services:
  backend:
    image: phoenix:1.4.0
    build: ./backend/
    command: ./start.sh
    ports:
      - "4000:4000"
    volumes:
      - ./backend/:/app
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: